#!/usr/bin/env node

import { spawn, spawnSync } from 'node:child_process';
import { existsSync, rmSync, writeFileSync } from 'node:fs';
import net from 'node:net';
import { basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(scriptDir, '..');
const isWindows = process.platform === 'win32';
const isDryRun = process.argv.includes('--dry-run');
const envLocalPath = resolve(rootDir, 'api/.env.local');
const portsPath = resolve(rootDir, '.ports');

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: rootDir,
    encoding: 'utf8',
    shell: isWindows,
    stdio: 'inherit',
    ...options,
  });

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(' ')} exited with ${result.status}`);
  }

  return result;
}

function deriveDatabaseName() {
  const worktreeName = basename(rootDir);
  const normalized = worktreeName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/_+$/g, '');
  return `ship_${normalized || 'dev'}`;
}

function databaseExists(databaseName) {
  const result = spawnSync('psql', ['-lqt'], {
    cwd: rootDir,
    encoding: 'utf8',
    shell: isWindows,
  });

  if (result.error || result.status !== 0) {
    const detail = result.stderr?.trim() || result.error?.message || 'psql -lqt failed';
    throw new Error(`Could not list PostgreSQL databases. Is local PostgreSQL running and is psql on PATH?\n${detail}`);
  }

  return result.stdout
    .split(/\r?\n/)
    .map((line) => line.split('|')[0]?.trim())
    .some((name) => name === databaseName);
}

function ensureEnvAndDatabase() {
  if (existsSync(envLocalPath)) {
    return;
  }

  const databaseName = deriveDatabaseName();
  const databaseUrl = `postgresql://localhost/${databaseName}`;

  if (isDryRun) {
    console.log(`[dry-run] Would create api/.env.local with DATABASE_URL for ${databaseName}`);
    return;
  }

  console.log(`Creating api/.env.local with DATABASE_URL for ${databaseName}...`);

  let needsSeed = false;
  if (!databaseExists(databaseName)) {
    console.log(`Creating database ${databaseName}...`);
    try {
      run('createdb', [databaseName], { stdio: 'inherit' });
      needsSeed = true;
    } catch (error) {
      console.error(`ERROR: Could not create database ${databaseName}`);
      console.error(`Please create it manually: createdb ${databaseName}`);
      throw error;
    }
  }

  writeFileSync(
    envLocalPath,
    `DATABASE_URL=${databaseUrl}\nSESSION_SECRET=dev-secret-change-in-production\n`,
    'utf8'
  );
  console.log('Created api/.env.local');

  if (needsSeed) {
    console.log('Setting up fresh database...');

    if (!existsSync(resolve(rootDir, 'node_modules'))) {
      console.log('Installing dependencies...');
      run('pnpm', ['install']);
    }

    run('pnpm', ['build:shared']);

    const dbEnv = { ...process.env, DATABASE_URL: databaseUrl };
    run('pnpm', ['exec', 'tsx', 'src/db/migrate.ts'], {
      cwd: resolve(rootDir, 'api'),
      env: dbEnv,
    });
    run('pnpm', ['exec', 'tsx', 'src/db/seed.ts'], {
      cwd: resolve(rootDir, 'api'),
      env: dbEnv,
    });

    console.log('Database setup complete!');
  }
}

function isPortAvailable(port) {
  return new Promise((resolveAvailable) => {
    const server = net.createServer();

    server.once('error', () => {
      resolveAvailable(false);
    });

    server.once('listening', () => {
      server.close(() => {
        resolveAvailable(true);
      });
    });

    server.listen(port);
  });
}

async function findAvailablePort(basePort) {
  const maxAttempts = 20;

  for (let offset = 0; offset < maxAttempts; offset += 1) {
    const port = basePort + offset;
    if (await isPortAvailable(port)) {
      return port;
    }
  }

  throw new Error(`Could not find available port after ${maxAttempts} attempts starting from ${basePort}`);
}

function writePortsFile(apiPort, webPort) {
  const contents = [
    '# Auto-generated by scripts/dev.mjs',
    "# This file shows which ports this worktree's dev server is using",
    '# DO NOT EDIT - will be overwritten on next dev start',
    `API=${apiPort}`,
    `WEB=${webPort}`,
    `STARTED=${new Date().toISOString()}`,
    `WORKTREE=${basename(rootDir)}`,
    '',
  ].join('\n');

  writeFileSync(portsPath, contents, 'utf8');
  console.log('Wrote .ports file');
}

function cleanupPortsFile() {
  if (existsSync(portsPath)) {
    rmSync(portsPath, { force: true });
    console.log('Cleaned up .ports file');
  }
}

async function main() {
  ensureEnvAndDatabase();

  console.log('Finding available ports...');
  const apiPort = await findAvailablePort(3000);
  const webPort = await findAvailablePort(5173);

  console.log(`Using API port: ${apiPort}`);
  console.log(`Using Web port: ${webPort}`);

  if (isDryRun) {
    console.log('[dry-run] Would write .ports file and start dev servers with:');
    console.log(`  API: http://localhost:${apiPort}`);
    console.log(`  Web: http://localhost:${webPort}`);
    return;
  }

  writePortsFile(apiPort, webPort);

  const childEnv = {
    ...process.env,
    PORT: String(apiPort),
    CORS_ORIGIN: `http://localhost:${webPort}`,
    VITE_PORT: String(webPort),
    VITE_API_URL: `http://localhost:${apiPort}`,
  };

  console.log('Starting dev servers...');
  console.log(`  API: http://localhost:${apiPort}`);
  console.log(`  Web: http://localhost:${webPort}`);
  console.log('');

  const child = spawn('pnpm', ['--parallel', '--recursive', 'run', 'dev'], {
    cwd: rootDir,
    env: childEnv,
    shell: isWindows,
    stdio: 'inherit',
  });

  const stop = (signal) => {
    if (!child.killed) {
      child.kill(signal);
    }
  };

  process.on('SIGINT', () => stop('SIGINT'));
  process.on('SIGTERM', () => stop('SIGTERM'));
  process.on('exit', cleanupPortsFile);

  child.on('exit', (code, signal) => {
    cleanupPortsFile();
    if (signal) {
      process.exit(signal === 'SIGINT' ? 130 : 1);
      return;
    }
    process.exit(code ?? 0);
  });

  child.on('error', (error) => {
    console.error(error);
    process.exit(1);
  });
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
